import { MapDefinition } from '../types'

export const castilloOlvidado: MapDefinition = {
  id: 'castillo_olvidado',
  name: 'Castillo Olvidado',
  width: 180,
  height: 180,
  biome: 'city',
  music: 'ambient_castillo_olvidado',
  spawns: [
    { id: 'santuario_entrada', position: { x: 10, z: 90 } },
    { id: 'ruinas_atajo', position: { x: 90, z: 10 } },
  ],
  portals: [
    {
      id: 'portal_to_santuario',
      position: { x: 4, z: 90 },
      radius: 4,
      targetMapId: 'santuario_olvidado',
      targetSpawnId: 'ruinas_gate',
      label: '→ Santuario Olvidado',
    },
    {
      id: 'portal_to_ruinas',
      position: { x: 90, z: 4 },
      radius: 4,
      targetMapId: 'ruinas_ancestrales',
      targetSpawnId: 'susurros_gate',
      label: '→ Ruinas Ancestrales',
    },
  ],
  npcs: [],
  monsters: [
    { monsterId: 'dark_guardian', position: { x: 40, z: 40 }, respawnSeconds: 15 },
    { monsterId: 'dark_guardian', position: { x: 100, z: 50 }, respawnSeconds: 15 },
    { monsterId: 'dark_guardian', position: { x: 60, z: 120 }, respawnSeconds: 15 },
    { monsterId: 'dark_guardian', position: { x: 140, z: 80 }, respawnSeconds: 15 },
    { monsterId: 'master_drainliar', position: { x: 70, z: 30 }, respawnSeconds: 12 },
    { monsterId: 'master_drainliar', position: { x: 110, z: 70 }, respawnSeconds: 12 },
    { monsterId: 'master_drainliar', position: { x: 50, z: 100 }, respawnSeconds: 12 },
    { monsterId: 'stalker', position: { x: 30, z: 70 }, respawnSeconds: 10 },
    { monsterId: 'stalker', position: { x: 130, z: 50 }, respawnSeconds: 10 },
    { monsterId: 'stalker', position: { x: 80, z: 130 }, respawnSeconds: 10 },
  ],
  props: [
    // Grand entrance gate
    { propId: 'ruin_pillar', position: { x: 6, z: 86 }, scale: 1.6 },
    { propId: 'ruin_pillar', position: { x: 6, z: 94 }, scale: 1.6 },
    // Outer wall columns (perimeter)
    { propId: 'ruin_column', position: { x: 20, z: 20 }, scale: 1.5 },
    { propId: 'ruin_column', position: { x: 160, z: 20 }, scale: 1.5 },
    { propId: 'ruin_column', position: { x: 20, z: 160 }, scale: 1.5 },
    { propId: 'ruin_column', position: { x: 160, z: 160 }, scale: 1.5 },
    { propId: 'ruin_column', position: { x: 90, z: 20 }, scale: 1.5 },
    { propId: 'ruin_column', position: { x: 20, z: 90 }, scale: 1.5 },
    { propId: 'ruin_column', position: { x: 160, z: 90 }, scale: 1.5 },
    { propId: 'ruin_column', position: { x: 90, z: 160 }, scale: 1.5 },
    // Inner keep pillars
    { propId: 'pillar', position: { x: 70, z: 70 }, scale: 1.4 },
    { propId: 'pillar', position: { x: 110, z: 70 }, scale: 1.4 },
    { propId: 'pillar', position: { x: 70, z: 110 }, scale: 1.4 },
    { propId: 'pillar', position: { x: 110, z: 110 }, scale: 1.4 },
    // Throne room
    { propId: 'ruin_pillar', position: { x: 85, z: 85 }, scale: 1.8 },
    { propId: 'ruin_pillar', position: { x: 95, z: 85 }, scale: 1.8 },
    { propId: 'ruin_slab', position: { x: 90, z: 90 }, scale: 1.5 },
    { propId: 'ruin_slab', position: { x: 92, z: 90 }, scale: 1.2 },
    { propId: 'ruin_slab', position: { x: 88, z: 90 }, scale: 1.2 },
    // Throne dais
    { propId: 'fountain', position: { x: 90, z: 90 }, scale: 0.6 },
    // Debris and rubble
    { propId: 'ruin_slab', position: { x: 40, z: 30 }, scale: 0.9 },
    { propId: 'ruin_slab', position: { x: 140, z: 50 }, scale: 1 },
    { propId: 'ruin_slab', position: { x: 30, z: 130 }, scale: 0.8 },
    { propId: 'ruin_slab', position: { x: 130, z: 140 }, scale: 1.1 },
    { propId: 'ruin_slab', position: { x: 60, z: 80 }, scale: 0.7 },
    { propId: 'ruin_slab', position: { x: 120, z: 100 }, scale: 0.9 },
    // Broken pillars
    { propId: 'ruin_column', position: { x: 50, z: 60 }, scale: 1.2 },
    { propId: 'ruin_column', position: { x: 130, z: 120 }, scale: 1.3 },
    { propId: 'ruin_column', position: { x: 80, z: 40 }, scale: 1.1 },
    { propId: 'ruin_column', position: { x: 100, z: 150 }, scale: 1.2 },
    // Rocks
    { propId: 'rock_a', position: { x: 35, z: 25 }, scale: 1 },
    { propId: 'rock_b', position: { x: 150, z: 30 }, scale: 1.2 },
    { propId: 'rock_c', position: { x: 25, z: 150 }, scale: 0.9 },
    { propId: 'rock_a', position: { x: 145, z: 145 }, scale: 1.1 },
    { propId: 'rock_b', position: { x: 60, z: 150 }, scale: 1 },
    // Torches along walls
    { propId: 'torch', position: { x: 15, z: 50 }, scale: 1.1 },
    { propId: 'torch', position: { x: 15, z: 80 }, scale: 1.1 },
    { propId: 'torch', position: { x: 15, z: 110 }, scale: 1.1 },
    { propId: 'torch', position: { x: 15, z: 140 }, scale: 1.1 },
    { propId: 'torch', position: { x: 165, z: 50 }, scale: 1.1 },
    { propId: 'torch', position: { x: 165, z: 80 }, scale: 1.1 },
    { propId: 'torch', position: { x: 165, z: 110 }, scale: 1.1 },
    { propId: 'torch', position: { x: 165, z: 140 }, scale: 1.1 },
    { propId: 'torch', position: { x: 50, z: 15 }, scale: 1.1 },
    { propId: 'torch', position: { x: 90, z: 15 }, scale: 1.1 },
    { propId: 'torch', position: { x: 130, z: 15 }, scale: 1.1 },
    { propId: 'torch', position: { x: 50, z: 165 }, scale: 1.1 },
    { propId: 'torch', position: { x: 90, z: 165 }, scale: 1.1 },
    { propId: 'torch', position: { x: 130, z: 165 }, scale: 1.1 },
    // Barrels and crates
    { propId: 'barrel', position: { x: 30, z: 45 }, scale: 0.7 },
    { propId: 'barrel', position: { x: 34, z: 45 }, scale: 0.7 },
    { propId: 'crate', position: { x: 150, z: 100 }, scale: 0.8 },
    { propId: 'crate', position: { x: 155, z: 100 }, scale: 0.8 },
    { propId: 'crate', position: { x: 150, z: 104 }, scale: 0.8 },
    // Outer yard fence remnants
    { propId: 'fence_stone', position: { x: 30, z: 50 }, scale: 0.9 },
    { propId: 'fence_stone', position: { x: 30, z: 130 }, scale: 0.9 },
    { propId: 'fence_stone', position: { x: 150, z: 50 }, scale: 0.9 },
    { propId: 'fence_stone', position: { x: 150, z: 130 }, scale: 0.9 },
  ],
}
