import { Achievement } from './types';

export const ALL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_steps',
    name: 'Primeros Pasos',
    condition: 'Completar la primera misión principal',
    reward: { zeny: 50 },
    unlocked: false,
  },
  {
    id: 'poring_hunter',
    name: 'Cazador de Porings',
    condition: 'Matar 15 Porings',
    reward: { zeny: 100, items: [{ itemId: 'poring_ear', name: 'Poring Ear', quantity: 1 }] },
    unlocked: false,
  },
  {
    id: 'job_change',
    name: 'Cambio de Rumbo',
    condition: 'Realizar el primer cambio de job',
    reward: { zeny: 100 },
    unlocked: false,
  },
  {
    id: 'mill_savior',
    name: 'El Molino Está a Salvo',
    condition: 'Completar la misión del molino (EPIC-06)',
    reward: { zeny: 200, title: 'Salvador del Molino' },
    unlocked: false,
  },
  {
    id: 'explorer',
    name: 'Explorador',
    condition: 'Descubrir 5 landmarks',
    reward: { zeny: 200 },
    unlocked: false,
  },
  {
    id: 'completionist',
    name: 'Completista',
    condition: 'Completar 5 misiones secundarias',
    reward: { zeny: 300 },
    unlocked: false,
  },
  {
    id: 'apprentice_hero',
    name: 'Aprendiz de Héroe',
    condition: 'Alcanzar nivel base 10',
    reward: { zeny: 100, title: 'Aprendiz de Héroe' },
    unlocked: false,
  },
  {
    id: 'warrior',
    name: 'Guerrero',
    condition: 'Alcanzar nivel base 15',
    reward: { zeny: 200, title: 'Guerrero', items: [{ itemId: 'copper_armor', name: 'Copper Armor', quantity: 1 }] },
    unlocked: false,
  },
  {
    id: 'bosque_entrance',
    name: 'El Bosque Susurrante',
    condition: 'Completar EPIC-08 (entrar al Bosque Umbrío)',
    reward: { zeny: 200, title: 'Explorador Sombrío' },
    unlocked: false,
  },
  {
    id: 'bosque_spirit',
    name: 'Amigo del Bosque',
    condition: 'Completar EPIC-09 (conocer al Espíritu del Bosque)',
    reward: { zeny: 300, title: 'Amigo del Bosque' },
    unlocked: false,
  },
  {
    id: 'bosque_ruins',
    name: 'Ruinas Ancestrales',
    condition: 'Completar EPIC-10 (descubrir las ruinas)',
    reward: { zeny: 400, title: 'Descubridor de Ruinas' },
    unlocked: false,
  },
  {
    id: 'bosque_cleanser',
    name: 'Purificador del Bosque',
    condition: 'Completar EPIC-11 (derrotar al Guardia Oscuro)',
    reward: { zeny: 600, title: 'Purificador' },
    unlocked: false,
  },
  {
    id: 'drainliar_hunter',
    name: 'Cazador de Drainliars',
    condition: 'Derrotar 30 Drainliars',
    reward: { zeny: 200 },
    unlocked: false,
  },
  {
    id: 'spore_hunter',
    name: 'Exterminador de Spores',
    condition: 'Derrotar 30 Spores',
    reward: { zeny: 200 },
    unlocked: false,
  },
  {
    id: 'wisp_hunter',
    name: 'Apagaluces',
    condition: 'Derrotar 30 Will o\' Wisps',
    reward: { zeny: 200 },
    unlocked: false,
  },
  {
    id: 'argiope_hunter',
    name: 'Tejedora Caída',
    condition: 'Derrotar 20 Argiopes',
    reward: { zeny: 200 },
    unlocked: false,
  },
  {
    id: 'shadow_cleanser',
    name: 'Sombra del Bosque',
    condition: 'Derrotar 100 criaturas en el Bosque Umbrío',
    reward: { zeny: 500, title: 'Sombra del Bosque' },
    unlocked: false,
  },
  {
    id: 'bu_material_collector',
    name: 'Coleccionista de Materiales',
    condition: 'Recolectar 5 tipos distintos de materiales del Bosque Umbrío',
    reward: { zeny: 300 },
    unlocked: false,
  },
  {
    id: 'crystal_gatherer',
    name: 'Acumulador de Cristales',
    condition: 'Recolectar 10 Cristales Oscuros',
    reward: { zeny: 400 },
    unlocked: false,
  },
  {
    id: 'tablet_reader',
    name: 'Lector de Tablillas',
    condition: 'Recolectar 8 Tablillas Antiguas',
    reward: { zeny: 350 },
    unlocked: false,
  },
  {
    id: 'shadow_explorer',
    name: 'Explorador Sombrío',
    condition: 'Descubrir todos los landmarks del Bosque Umbrío',
    reward: { zeny: 400 },
    unlocked: false,
  },
  {
    id: 'ruins_visitor',
    name: 'Visitante de Ruinas',
    condition: 'Visitar las 4 zonas del Bosque Umbrío',
    reward: { zeny: 300 },
    unlocked: false,
  },
  {
    id: 'sanctuary_reached',
    name: 'Llegada al Santuario',
    condition: 'Alcanzar el Santuario Olvidado',
    reward: { zeny: 250 },
    unlocked: false,
  },
  {
    id: 'shadow_warrior',
    name: 'Guerrero de las Sombras',
    condition: 'Alcanzar nivel base 25',
    reward: { zeny: 500, title: 'Cazador de Sombras' },
    unlocked: false,
  },
  {
    id: 'forest_master',
    name: 'Señor del Bosque',
    condition: 'Alcanzar nivel base 30',
    reward: { zeny: 1000, title: 'Señor del Bosque Umbrío' },
    unlocked: false,
  },
  {
    id: 'bu_side_quest_master',
    name: 'Completista Umbrío',
    condition: 'Completar 8 misiones secundarias del Bosque Umbrío',
    reward: { zeny: 600 },
    unlocked: false,
  },
  {
    id: 'bu_epic_hero',
    name: 'Héroe del Bosque Umbrío',
    condition: 'Completar todas las misiones principales del Bosque Umbrío',
    reward: { zeny: 800, title: 'Leyenda del Bosque' },
    unlocked: false,
  },
  {
    id: 'bu_completionist',
    name: 'Dominio del Bosque Umbrío',
    condition: 'Completar TODAS las misiones del Bosque Umbrío (14)',
    reward: { zeny: 1500, title: 'Guardián del Bosque' },
    unlocked: false,
  },
];

export const TITLES: Record<string, { name: string; achievementId: string }> = {
  'mill_savior': { name: 'Salvador del Molino', achievementId: 'mill_savior' },
  'apprentice_hero': { name: 'Aprendiz de Héroe', achievementId: 'apprentice_hero' },
  'warrior': { name: 'Guerrero', achievementId: 'warrior' },
  'bosque_entrance': { name: 'Explorador Sombrío', achievementId: 'bosque_entrance' },
  'bosque_spirit': { name: 'Amigo del Bosque', achievementId: 'bosque_spirit' },
  'bosque_ruins': { name: 'Descubridor de Ruinas', achievementId: 'bosque_ruins' },
  'bosque_cleanser': { name: 'Purificador', achievementId: 'bosque_cleanser' },
  'shadow_cleanser': { name: 'Sombra del Bosque', achievementId: 'shadow_cleanser' },
  'shadow_warrior': { name: 'Cazador de Sombras', achievementId: 'shadow_warrior' },
  'forest_master': { name: 'Señor del Bosque Umbrío', achievementId: 'forest_master' },
  'bu_epic_hero': { name: 'Leyenda del Bosque', achievementId: 'bu_epic_hero' },
  'bu_completionist': { name: 'Guardián del Bosque', achievementId: 'bu_completionist' },
};
