import { QuestDefinition } from './types';

export const ALL_QUESTS: QuestDefinition[] = [
  // === MAIN QUESTS ===
  {
    id: 'epic_01',
    name: 'El Despertar del Héroe',
    description: 'Habla con Kafra Assistant Clarice y el Swordsman Instructor Kurt en Prontera.',
    zoneId: 'prontera_city',
    npcGiver: 'Kafra Assistant ★ Clarice',
    npcGiverId: 'npc_kafra',
    isMainQuest: true,
    state: 'available',
    objectives: [
      { type: 'talk', description: 'Habla con Clarice', count: 1, current: 0, targetId: 'npc_kafra' },
      { type: 'talk', description: 'Habla con el Instructor Kurt', count: 1, current: 0, targetId: 'npc_crusader' },
    ],
    rewards: { zeny: 50, baseExp: 25, jobExp: 25 },
  },
  {
    id: 'epic_02',
    name: 'La Primera Cacería',
    description: 'Kurt te envía a los campos del este para cazar Porings. Demuestra tu valía.',
    zoneId: 'campo_manana_1',
    npcGiver: 'Swordsman Instructor ★ Kurt',
    npcGiverId: 'npc_crusader',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_01',
    requiredLevel: 2,
    objectives: [
      { type: 'kill', description: 'Matar Porings', count: 3, current: 0, mobType: 'poring', location: { zoneId: 'campo_manana_1', x: 32, z: 0 } },
    ],
    rewards: { zeny: 100, baseExp: 50, jobExp: 50, items: [{ itemId: 'red_potion', name: 'Red Potion', quantity: 1 }] },
  },
  {
    id: 'epic_03',
    name: 'El Lunático Problemático',
    description: 'Un Lunático gigante está destruyendo las cosechas. Encuéntralo en los campos del este.',
    zoneId: 'campo_manana_1',
    npcGiver: 'Swordsman Instructor ★ Kurt',
    npcGiverId: 'npc_crusader',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_02',
    objectives: [
      { type: 'kill', description: 'Matar Lunáticos', count: 5, current: 0, mobType: 'lunatic', location: { zoneId: 'campo_manana_1', x: 48, z: 20 } },
      { type: 'kill', description: 'Derrotar al Lunático Gigante', count: 1, current: 0, mobType: 'lunatic', location: { zoneId: 'campo_manana_1', x: 48, z: 20 } },
    ],
    rewards: { zeny: 150, baseExp: 120, jobExp: 100, items: [{ itemId: 'training_sword', name: 'Training Sword', quantity: 1 }] },
  },
  {
    id: 'epic_04',
    name: 'El Camino Hacia el Poder',
    description: 'Kurt dice que es hora de elegir un camino. Alcanza nivel 10 y cambia de job.',
    zoneId: 'prontera_city',
    npcGiver: 'Swordsman Instructor ★ Kurt',
    npcGiverId: 'npc_crusader',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_03',
    requiredLevel: 8,
    objectives: [
      { type: 'reach', description: 'Alcanzar nivel base 10', count: 10, current: 0 },
      { type: 'talk', description: 'Cambiar de job con Kurt', count: 1, current: 0, targetId: 'npc_crusader' },
    ],
    rewards: { zeny: 200, baseExp: 0, jobExp: 80 },
  },
  {
    id: 'epic_05',
    name: 'La Plaga de los Écoles',
    description: 'Clarice recibe noticias urgentes. Los Fabres y Chonchons amenazan la ruta comercial.',
    zoneId: 'campo_manana_2',
    npcGiver: 'Kafra Assistant ★ Clarice',
    npcGiverId: 'npc_kafra',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_04',
    objectives: [
      { type: 'kill', description: 'Matar Fabres', count: 8, current: 0, mobType: 'fabre', location: { zoneId: 'campo_manana_2', x: 64, z: 0 } },
      { type: 'kill', description: 'Matar Chonchons', count: 5, current: 0, mobType: 'chonchon', location: { zoneId: 'campo_manana_2', x: 64, z: 0 } },
    ],
    rewards: { zeny: 300, baseExp: 300, jobExp: 220, items: [{ itemId: 'ring_of_life', name: 'Ring of Life', quantity: 1 }] },
  },
  {
    id: 'epic_06',
    name: 'El Molino Silenciado',
    description: 'El molino de viento ha dejado de funcionar. Investiga qué ocurre en las Laderas del Molino.',
    zoneId: 'campo_manana_3',
    npcGiver: 'Guardia de Prontera',
    npcGiverId: 'npc_guard',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_05',
    objectives: [
      { type: 'kill', description: 'Matar Savage Babies', count: 6, current: 0, mobType: 'savage_baby', location: { zoneId: 'campo_manana_3', x: 12, z: 40 } },
      { type: 'kill', description: 'Matar Pickies', count: 4, current: 0, mobType: 'picky', location: { zoneId: 'campo_manana_3', x: 12, z: 40 } },
      { type: 'kill', description: 'Derrotar a la Mandrágora Gigante', count: 1, current: 0, mobType: 'mandragora', location: { zoneId: 'campo_manana_3', x: 16, z: 48 } },
    ],
    rewards: { zeny: 500, baseExp: 800, jobExp: 600, items: [{ itemId: 'leather_armor', name: 'Leather Armor', quantity: 1 }] },
  },
  {
    id: 'epic_07',
    name: 'El Velo del Este',
    description: 'Clarice revela que el Camino del Este está siendo tomado por monstruos. Despeja la ruta.',
    zoneId: 'camino_este',
    npcGiver: 'Kafra Assistant ★ Clarice',
    npcGiverId: 'npc_kafra',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_06',
    objectives: [
      { type: 'kill', description: 'Matar Pickies del bosque', count: 5, current: 0, mobType: 'picky', location: { zoneId: 'camino_este', x: 96, z: 0 } },
      { type: 'kill', description: 'Matar PecoPecos', count: 3, current: 0, mobType: 'pecopeco', location: { zoneId: 'camino_este', x: 96, z: 0 } },
      { type: 'explore', description: 'Llegar al final del Camino del Este', count: 1, current: 0, location: { zoneId: 'camino_este', x: 128, z: 0 } },
    ],
    rewards: { zeny: 400, baseExp: 500, jobExp: 400, items: [{ itemId: 'wing_boots', name: 'Wing Boots', quantity: 1 }] },
  },
  // === SIDE QUESTS ===
  {
    id: 'sq_01',
    name: 'El Gremio Necesita Madera',
    description: 'Kurt necesita Jellopies para reparar el equipo del gremio.',
    zoneId: 'campo_manana_1',
    npcGiver: 'Swordsman Instructor ★ Kurt',
    npcGiverId: 'npc_crusader',
    state: 'available',
    objectives: [
      { type: 'collect', description: 'Recolectar 8 Jellopy (drop de Poring)', count: 8, current: 0, targetId: 'jellopy' },
    ],
    rewards: { zeny: 80, baseExp: 45, jobExp: 30 },
  },
  {
    id: 'sq_02',
    name: 'El Gato de Clarice',
    description: 'El gato de Clarice se perdió en CM1. ¿Puedes encontrarlo?',
    zoneId: 'campo_manana_1',
    npcGiver: 'Kafra Assistant ★ Clarice',
    npcGiverId: 'npc_kafra',
    state: 'available',
    objectives: [
      { type: 'explore', description: 'Encontrar al gato perdido en CM1', count: 1, current: 0, location: { zoneId: 'campo_manana_1', x: 42, z: 14 } },
    ],
    rewards: { zeny: 60, baseExp: 30, jobExp: 20, items: [{ itemId: 'cat_whisker', name: "Cat's Whisker", quantity: 1 }] },
  },
  {
    id: 'sq_03',
    name: 'Entregas al Molino',
    description: 'Lleva este paquete urgente al molinero en CM3.',
    zoneId: 'campo_manana_3',
    npcGiver: 'Mensajero de Prontera',
    npcGiverId: 'npc_messenger',
    state: 'available',
    objectives: [
      { type: 'talk', description: 'Llevar el paquete al molinero', count: 1, current: 0, targetId: 'npc_miller' },
    ],
    rewards: { zeny: 120, baseExp: 100, jobExp: 60 },
  },
  {
    id: 'sq_04',
    name: 'Flores para la Plaza',
    description: 'El jardinero necesita materiales para embellecer la plaza.',
    zoneId: 'campo_manana_2',
    npcGiver: 'Jardinero de Prontera',
    npcGiverId: 'npc_gardener',
    state: 'available',
    objectives: [
      { type: 'collect', description: 'Recolectar 5 Sticky Mucus (Fabre)', count: 5, current: 0, targetId: 'sticky_mucus' },
    ],
    rewards: { zeny: 100, baseExp: 80, jobExp: 50 },
  },
  {
    id: 'sq_05',
    name: 'Primeros Auxilios',
    description: 'El guardia de CM3 necesita provisiones médicas.',
    zoneId: 'campo_manana_3',
    npcGiver: 'Kafra Assistant ★ Clarice',
    npcGiverId: 'npc_kafra',
    state: 'available',
    requiredQuestId: 'epic_03',
    objectives: [
      { type: 'talk', description: 'Llevar 3 Red Potions al guardia de CM3', count: 1, current: 0, targetId: 'npc_guard' },
    ],
    rewards: { zeny: 80, baseExp: 60, jobExp: 40 },
  },
  {
    id: 'sq_06',
    name: 'Marcas de Cacería',
    description: 'Kurt premia a los cazadores de Porings más dedicados.',
    zoneId: 'campo_manana_1',
    npcGiver: 'Swordsman Instructor ★ Kurt',
    npcGiverId: 'npc_crusader',
    state: 'available',
    objectives: [
      { type: 'kill', description: 'Matar Porings (total acumulativo)', count: 15, current: 0, mobType: 'poring' },
    ],
    rewards: { zeny: 200, baseExp: 150, jobExp: 100, items: [{ itemId: 'poring_ear', name: 'Poring Ear', quantity: 1 }] },
  },
  {
    id: 'sq_07',
    name: 'El Guardián del Molino',
    description: 'Protege el molino de las oleadas de Savage Babies.',
    zoneId: 'campo_manana_3',
    npcGiver: 'Mol Molinero',
    npcGiverId: 'npc_miller',
    state: 'locked',
    requiredQuestId: 'epic_06',
    objectives: [
      { type: 'survive', description: 'Proteger el molino', count: 1, current: 0, location: { zoneId: 'campo_manana_3', x: 12, z: 40 } },
    ],
    rewards: { zeny: 250, baseExp: 300, jobExp: 200 },
  },
  {
    id: 'sq_08',
    name: 'Plumas de Chonchon',
    description: 'El artesano necesita alas de Chonchon para sus flechas.',
    zoneId: 'campo_manana_2',
    npcGiver: 'Artesano de Prontera',
    npcGiverId: 'npc_artisan',
    state: 'available',
    objectives: [
      { type: 'collect', description: 'Recolectar 8 Chonchon Wings', count: 8, current: 0, targetId: 'chonchon_wing' },
    ],
    rewards: { zeny: 150, baseExp: 120, jobExp: 80 },
  },
  {
    id: 'sq_09',
    name: 'Receta Secreta',
    description: 'El cocinero necesita huevos de Picky para su receta especial.',
    zoneId: 'camino_este',
    npcGiver: 'Cocinero de Prontera',
    npcGiverId: 'npc_chef',
    state: 'available',
    objectives: [
      { type: 'collect', description: 'Traer 3 Picky Eggs', count: 3, current: 0, targetId: 'picky_egg' },
    ],
    rewards: { zeny: 200, baseExp: 180, jobExp: 120, items: [{ itemId: 'apple_of_the_sun', name: 'Apple of the Sun', quantity: 1 }] },
  },
  {
    id: 'sq_10',
    name: 'El Huevo Perdido',
    description: 'Un granjero perdió un huevo de PecoPeco en el Camino del Este.',
    zoneId: 'camino_este',
    npcGiver: 'Granjero de Prontera',
    npcGiverId: 'npc_farmer',
    state: 'available',
    objectives: [
      { type: 'explore', description: 'Encontrar el huevo de PecoPeco en el Camino del Este', count: 1, current: 0, location: { zoneId: 'camino_este', x: 108, z: 8 } },
    ],
    rewards: { zeny: 130, baseExp: 90, jobExp: 60 },
  },
  {
    id: 'sq_11',
    name: 'Herbolaria',
    description: 'La curandera necesita hierbas verdes para sus pociones.',
    zoneId: 'campo_manana_1',
    npcGiver: 'Curandera de Prontera',
    npcGiverId: 'npc_healer',
    state: 'available',
    objectives: [
      { type: 'collect', description: 'Recolectar 10 hierbas verdes', count: 10, current: 0, targetId: 'green_herb' },
    ],
    rewards: { zeny: 90, baseExp: 70, jobExp: 50 },
  },
  {
    id: 'sq_12',
    name: 'El Primer Paso',
    description: 'Adéntrate en la Mazmorra de Entrenamiento y sal victorioso.',
    zoneId: 'training_dungeon',
    npcGiver: 'Guardia de la Mazmorra',
    npcGiverId: 'npc_guard',
    state: 'available',
    requiredLevel: 5,
    objectives: [
      { type: 'explore', description: 'Llegar al final de la mazmorra', count: 1, current: 0, location: { zoneId: 'training_dungeon', x: 0, z: -56 } },
    ],
    rewards: { zeny: 350, baseExp: 400, jobExp: 300, items: [{ itemId: 'training_amulet', name: 'Training Amulet', quantity: 1 }] },
  },
  {
    id: 'sq_13',
    name: 'Luz en la Oscuridad',
    description: 'Activa las antorchas de la mazmorra para iluminar el camino.',
    zoneId: 'training_dungeon',
    npcGiver: 'Guardia de la Mazmorra',
    npcGiverId: 'npc_guard',
    state: 'available',
    objectives: [
      { type: 'explore', description: 'Activar antorcha 1', count: 1, current: 0, interactId: 'dungeon_torch_1', location: { zoneId: 'training_dungeon', x: 12, z: -48 } },
      { type: 'explore', description: 'Activar antorcha 2', count: 1, current: 0, interactId: 'dungeon_torch_2', location: { zoneId: 'training_dungeon', x: 24, z: -52 } },
      { type: 'explore', description: 'Activar antorcha 3', count: 1, current: 0, interactId: 'dungeon_torch_3', location: { zoneId: 'training_dungeon', x: 36, z: -56 } },
    ],
    rewards: { zeny: 200, baseExp: 250, jobExp: 180 },
  },
  {
    id: 'sq_14',
    name: 'Ecos del Pasado',
    description: 'Lee las inscripciones antiguas en las paredes de la mazmorra.',
    zoneId: 'training_dungeon',
    npcGiver: 'Guardia de la Mazmorra',
    npcGiverId: 'npc_guard',
    state: 'available',
    objectives: [
      { type: 'explore', description: 'Leer inscripción del este', count: 1, current: 0, interactId: 'dungeon_inscription_1', location: { zoneId: 'training_dungeon', x: 8, z: -44 } },
      { type: 'explore', description: 'Leer inscripción del oeste', count: 1, current: 0, interactId: 'dungeon_inscription_2', location: { zoneId: 'training_dungeon', x: 30, z: -60 } },
    ],
    rewards: { zeny: 150, baseExp: 180, jobExp: 120 },
  },
  {
    id: 'sq_15',
    name: 'Depuración Total',
    description: 'Limpia la mazmorra de todos los monstruos.',
    zoneId: 'training_dungeon',
    npcGiver: 'Guardia de la Mazmorra',
    npcGiverId: 'npc_guard',
    state: 'available',
    objectives: [
      { type: 'kill', description: 'Matar monstruos en la mazmorra', count: 15, current: 0 },
    ],
    rewards: { zeny: 400, baseExp: 500, jobExp: 400 },
  },
  // === BOSQUE UMBRÍO EPIC QUESTS ===
  {
    id: 'epic_08',
    name: 'El Bosque Susurrante',
    description: 'El Guardia del Bosque Umbrío te detiene en la entrada. Algo oscuro se agita en el interior.',
    zoneId: 'bosque_umbrio_entrada',
    npcGiver: 'Guardia del Bosque Umbrío',
    npcGiverId: 'npc_bosque_guard',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_07',
    requiredLevel: 15,
    objectives: [
      { type: 'talk', description: 'Hablar con el Guardia del Bosque Umbrío', count: 1, current: 0, targetId: 'npc_bosque_guard' },
      { type: 'explore', description: 'Adentrarse en el Bosque Umbrío', count: 1, current: 0, location: { zoneId: 'bosque_umbrio_entrada', x: 120, z: 16 } },
    ],
    rewards: { zeny: 500, baseExp: 600, jobExp: 450 },
  },
  {
    id: 'epic_09',
    name: 'Corrupción Profunda',
    description: 'El bosque está siendo corrompido. Busca al Espíritu del Bosque en lo profundo.',
    zoneId: 'bosque_umbrio_profundo',
    npcGiver: 'Guardia del Bosque Umbrío',
    npcGiverId: 'npc_bosque_guard',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_08',
    objectives: [
      { type: 'kill', description: 'Derrotar Will o\' Wisps', count: 8, current: 0, mobType: 'will_o_wisp', location: { zoneId: 'bosque_umbrio_profundo', x: 128, z: 40 } },
      { type: 'kill', description: 'Derrotar Argiopes', count: 5, current: 0, mobType: 'argiope', location: { zoneId: 'bosque_umbrio_profundo', x: 128, z: 40 } },
      { type: 'talk', description: 'Hablar con el Espíritu del Bosque', count: 1, current: 0, targetId: 'npc_spirit' },
    ],
    rewards: { zeny: 800, baseExp: 900, jobExp: 700, items: [{ itemId: 'wisp_amulet', name: 'Amuleto de Fuego Fatuo', quantity: 1 }] },
  },
  {
    id: 'epic_10',
    name: 'Secretos del Pasado',
    description: 'El Espíritu del Bosque revela que las Ruinas Ancestrales guardan la clave de la corrupción.',
    zoneId: 'ruinas_ancestrales',
    npcGiver: 'Espíritu del Bosque',
    npcGiverId: 'npc_spirit',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_09',
    objectives: [
      { type: 'explore', description: 'Llegar a las Ruinas Ancestrales', count: 1, current: 0, location: { zoneId: 'ruinas_ancestrales', x: 168, z: 12 } },
      { type: 'kill', description: 'Derrotar Acechadores', count: 6, current: 0, mobType: 'stalker', location: { zoneId: 'ruinas_ancestrales', x: 168, z: 12 } },
      { type: 'collect', description: 'Encontrar Tablillas Antiguas', count: 4, current: 0, targetId: 'ancient_tablet' },
      { type: 'talk', description: 'Hablar con el Arqueólogo Eldric', count: 1, current: 0, targetId: 'npc_archaeologist' },
    ],
    rewards: { zeny: 1000, baseExp: 1200, jobExp: 900, items: [{ itemId: 'ancient_seal', name: 'Sello Ancestral', quantity: 1 }] },
  },
  {
    id: 'epic_11',
    name: 'El Santuario Final',
    description: 'El mal tiene su origen en el Santuario Olvidado. Enfréntate al Guardia Oscuro.',
    zoneId: 'santuario_olvidado',
    npcGiver: 'Sabio Mathius',
    npcGiverId: 'npc_sage',
    isMainQuest: true,
    state: 'locked',
    requiredQuestId: 'epic_10',
    requiredLevel: 20,
    objectives: [
      { type: 'explore', description: 'Alcanzar el Santuario Olvidado', count: 1, current: 0, location: { zoneId: 'santuario_olvidado', x: 160, z: 40 } },
      { type: 'talk', description: 'Hablar con el Sabio Mathius', count: 1, current: 0, targetId: 'npc_sage' },
      { type: 'kill', description: 'Derrotar al Drainliar Supremo', count: 1, current: 0, mobType: 'master_drainliar', location: { zoneId: 'santuario_olvidado', x: 168, z: 52 } },
      { type: 'kill', description: 'Derrotar al Guardia Oscuro', count: 1, current: 0, mobType: 'dark_guardian', location: { zoneId: 'santuario_olvidado', x: 168, z: 52 } },
    ],
    rewards: { zeny: 2000, baseExp: 2500, jobExp: 2000, items: [{ itemId: 'ancient_crown', name: 'Corona Ancestral', quantity: 1 }] },
  },
  // === BOSQUE UMBRÍO SIDE QUESTS ===
  {
    id: 'sq_16',
    name: 'Caza Nocturna',
    description: 'Los Drainliars están multiplicándose. Adelgaza su población.',
    zoneId: 'bosque_umbrio_entrada',
    npcGiver: 'Guardia del Bosque Umbrío',
    npcGiverId: 'npc_bosque_guard',
    state: 'locked',
    requiredQuestId: 'epic_08',
    objectives: [
      { type: 'kill', description: 'Derrotar Drainliars Sombríos', count: 10, current: 0, mobType: 'drainliar', location: { zoneId: 'bosque_umbrio_entrada', x: 120, z: 16 } },
    ],
    rewards: { zeny: 400, baseExp: 350, jobExp: 250, items: [{ itemId: 'bat_hood', name: 'Capucha de Murciélago', quantity: 1 }] },
  },
  {
    id: 'sq_17',
    name: 'Esporas Venenosas',
    description: 'El Mercader Sombrío necesita esporas para sus pociones.',
    zoneId: 'bosque_umbrio_entrada',
    npcGiver: 'Mercader Sombrío',
    npcGiverId: 'npc_shady_merchant',
    state: 'locked',
    requiredQuestId: 'epic_08',
    objectives: [
      { type: 'collect', description: 'Recolectar Polvo de Spore', count: 8, current: 0, targetId: 'spore_powder' },
    ],
    rewards: { zeny: 300, baseExp: 280, jobExp: 200 },
  },
  {
    id: 'sq_18',
    name: 'Luces Errante',
    description: 'Los fuegos fatuos confunden a los viajeros. Hay que reducir su número.',
    zoneId: 'bosque_umbrio_profundo',
    npcGiver: 'Espíritu del Bosque',
    npcGiverId: 'npc_spirit',
    state: 'locked',
    requiredQuestId: 'epic_09',
    objectives: [
      { type: 'kill', description: 'Derrotar Will o\' Wisps', count: 8, current: 0, mobType: 'will_o_wisp', location: { zoneId: 'bosque_umbrio_profundo', x: 128, z: 40 } },
    ],
    rewards: { zeny: 450, baseExp: 400, jobExp: 300 },
  },
  {
    id: 'sq_19',
    name: 'Telaraña Mortal',
    description: 'Las Argiopes están tejiendo telarañas en todo el bosque profundo.',
    zoneId: 'bosque_umbrio_profundo',
    npcGiver: 'Espíritu del Bosque',
    npcGiverId: 'npc_spirit',
    state: 'locked',
    requiredQuestId: 'epic_09',
    objectives: [
      { type: 'kill', description: 'Derrotar Argiopes Tejedoras', count: 6, current: 0, mobType: 'argiope', location: { zoneId: 'bosque_umbrio_profundo', x: 140, z: 44 } },
    ],
    rewards: { zeny: 500, baseExp: 450, jobExp: 350, items: [{ itemId: 'silk_armor', name: 'Armadura de Seda', quantity: 1 }] },
  },
  {
    id: 'sq_20',
    name: 'Brillo Natural',
    description: 'El Mercader Sombrío busca savia de las Plantas Radiantes.',
    zoneId: 'bosque_umbrio_profundo',
    npcGiver: 'Mercader Sombrío',
    npcGiverId: 'npc_shady_merchant',
    state: 'locked',
    requiredQuestId: 'epic_09',
    objectives: [
      { type: 'collect', description: 'Recolectar Savia Brillante', count: 5, current: 0, targetId: 'glowing_sap' },
    ],
    rewards: { zeny: 350, baseExp: 320, jobExp: 240, items: [{ itemId: 'wisp_circlet', name: 'Aro de Fuego Fatuo', quantity: 1 }] },
  },
  {
    id: 'sq_21',
    name: 'Sombras Merodeadoras',
    description: 'Los Acechadores de Sombras merodean por las ruinas. Limpia el área.',
    zoneId: 'ruinas_ancestrales',
    npcGiver: 'Arqueólogo Eldric',
    npcGiverId: 'npc_archaeologist',
    state: 'locked',
    requiredQuestId: 'epic_10',
    objectives: [
      { type: 'kill', description: 'Derrotar Acechadores de Sombras', count: 5, current: 0, mobType: 'stalker', location: { zoneId: 'ruinas_ancestrales', x: 168, z: 12 } },
    ],
    rewards: { zeny: 600, baseExp: 550, jobExp: 400, items: [{ itemId: 'shadow_veil', name: 'Velo de Sombra', quantity: 1 }] },
  },
  {
    id: 'sq_22',
    name: 'Tablillas del Pasado',
    description: 'Eldric necesita más tablillas para descifrar los secretos de las ruinas.',
    zoneId: 'ruinas_ancestrales',
    npcGiver: 'Arqueólogo Eldric',
    npcGiverId: 'npc_archaeologist',
    state: 'locked',
    requiredQuestId: 'epic_10',
    objectives: [
      { type: 'collect', description: 'Recolectar Tablillas Antiguas', count: 4, current: 0, targetId: 'ancient_tablet' },
    ],
    rewards: { zeny: 500, baseExp: 480, jobExp: 360, items: [{ itemId: 'shadow_robe', name: 'Túnica Sombría', quantity: 1 }] },
  },
  {
    id: 'sq_23',
    name: 'Supervivencia en las Ruinas',
    description: 'Permanece en las ruinas el tiempo suficiente para ahuyentar a las sombras.',
    zoneId: 'ruinas_ancestrales',
    npcGiver: 'Arqueólogo Eldric',
    npcGiverId: 'npc_archaeologist',
    state: 'locked',
    requiredQuestId: 'epic_10',
    objectives: [
      { type: 'survive', description: 'Sobrevivir en las Ruinas Ancestrales', count: 1, current: 0, location: { zoneId: 'ruinas_ancestrales', x: 168, z: 12 } },
    ],
    rewards: { zeny: 700, baseExp: 600, jobExp: 450 },
  },
  {
    id: 'sq_24',
    name: 'Cristal Oscuro',
    description: 'El Sabio Mathius necesita cristales oscuros para sellar el portal.',
    zoneId: 'santuario_olvidado',
    npcGiver: 'Sabio Mathius',
    npcGiverId: 'npc_sage',
    state: 'locked',
    requiredQuestId: 'epic_11',
    objectives: [
      { type: 'collect', description: 'Recolectar Cristales Oscuros', count: 2, current: 0, targetId: 'dark_crystal' },
    ],
    rewards: { zeny: 800, baseExp: 700, jobExp: 550, items: [{ itemId: 'bat_ring', name: 'Anillo de Murciélago', quantity: 1 }] },
  },
  {
    id: 'sq_25',
    name: 'Purificación del Bosque',
    description: 'El Sabio Mathius te pide que limpies el bosque de toda corrupción.',
    zoneId: 'santuario_olvidado',
    npcGiver: 'Sabio Mathius',
    npcGiverId: 'npc_sage',
    state: 'locked',
    requiredQuestId: 'epic_11',
    objectives: [
      { type: 'kill', description: 'Derrotar criaturas del Bosque Umbrío', count: 30, current: 0 },
    ],
    rewards: { zeny: 1200, baseExp: 1200, jobExp: 900, items: [{ itemId: 'ancient_plate', name: 'Coraza Ancestral', quantity: 1 }] },
  },
];

export const LANDMARKS = [
  { id: 'lm_fountain', name: 'La Fuente de Prontera', zoneId: 'prontera_city', x: 0, z: 6 },
  { id: 'lm_castle', name: 'El Castillo', zoneId: 'prontera_city', x: 0, z: -12 },
  { id: 'lm_tree', name: 'El Árbol Centinela', zoneId: 'campo_manana_1', x: 20, z: 10 },
  { id: 'lm_ruins', name: 'Las Ruinas Antiguas', zoneId: 'campo_manana_2', x: 48, z: 8 },
  { id: 'lm_mill', name: 'El Molino', zoneId: 'campo_manana_3', x: 12, z: 40 },
  { id: 'lm_mirador', name: 'El Mirador del Este', zoneId: 'camino_este', x: 120, z: 12 },
  { id: 'lm_altar', name: 'El Altar Subterráneo', zoneId: 'training_dungeon', x: 16, z: -56 },
  { id: 'lm_bosque_arch', name: 'El Arco del Bosque Umbrío', zoneId: 'bosque_umbrio_entrada', x: 112, z: 12 },
  { id: 'lm_weeping_willow', name: 'El Sauce Llorón', zoneId: 'bosque_umbrio_profundo', x: 140, z: 24 },
  { id: 'lm_ruined_temple', name: 'El Templo en Ruinas', zoneId: 'ruinas_ancestrales', x: 168, z: 12 },
  { id: 'lm_forgotten_shrine', name: 'El Santuario Olvidado', zoneId: 'santuario_olvidado', x: 160, z: 40 },
  { id: 'lm_dark_portal', name: 'El Portal Oscuro', zoneId: 'santuario_olvidado', x: 168, z: 52 },
];
