export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  '2xl': 32,
  '3xl': 48,
} as const;

export const colors = {
  parchment: 'var(--ui-parchment)',
  brown: 'var(--ui-brown)',
  darkBrown: 'var(--ui-dark-brown)',
  gold: 'var(--ui-gold)',
  hp: 'var(--ui-red-hp)',
  sp: 'var(--ui-blue-sp)',
  disabled: 'var(--ui-disabled)',
  ivory: 'var(--ui-ivory)',
  oldPaper: 'var(--ui-old-paper)',
  warmBeige: 'var(--ui-warm-beige)',
  bronze: 'var(--ui-bronze)',
  expPurple: 'var(--ui-exp-purple)',
  bgDark: 'var(--ui-bg-dark)',
  textPrimary: 'var(--ui-text-primary)',
  textSecondary: 'var(--ui-text-secondary)',
  textGray: 'var(--ui-text-gray)',
  textMuted: 'var(--ui-text-muted)',
  hpBg: 'var(--ui-red-hp-bg)',
  spBg: 'var(--ui-blue-sp-bg)',
  goldBg: 'var(--ui-gold-bg)',
  expBg: 'var(--ui-exp-bg)',
  expPurpleBg: 'var(--ui-exp-purple-bg)',
  overlayDark: 'var(--ui-overlay-dark)',
  overlayMedium: 'var(--ui-overlay-medium)',
  overlayLight: 'var(--ui-overlay-light)',
  overlayDarker: 'var(--ui-overlay-darker)',
  hpSoft: 'var(--ui-hp-soft)',
  goldSoft: 'var(--ui-gold-soft)',
  brownSoft: 'var(--ui-brown-soft)',
  overlayHeavy: 'var(--ui-overlay-heavy)',
  overlayWindow: 'var(--ui-overlay-window)',
  glassDark: 'var(--ui-glass-dark)',
  glassMedium: 'var(--ui-glass-medium)',
  glassLight: 'var(--ui-glass-light)',
  glassCard: 'var(--ui-glass-card)',
  glassBg: 'var(--ui-glass-bg)',
  glassExtra: 'var(--ui-glass-extra)',
  accentIndigo: 'var(--ui-accent-indigo)',
  accentIndigoBg: 'var(--ui-accent-indigo-bg)',
  accentAmber: 'var(--ui-accent-amber)',
  accentAmberBg: 'var(--ui-accent-amber-bg)',
  accentGreen: 'var(--ui-accent-green)',
  accentGreenBright: 'var(--ui-accent-green-bright)',
  accentGreenBg: 'var(--ui-accent-green-bg)',
  accentRed: 'var(--ui-accent-red)',
  accentRedBg: 'var(--ui-accent-red-bg)',
  accentBlue: 'var(--ui-accent-blue)',
  accentBlueSoft: 'var(--ui-accent-blue-soft)',
  accentPurple: 'var(--ui-accent-purple)',
  disabledBg: 'var(--ui-disabled-bg)',
  accentGreenBrightBg: 'var(--ui-accent-green-bright-bg)',
  textWhiteFaint: 'var(--ui-text-white-faint)',
  textWhiteLight: 'var(--ui-text-white-light)',
  textWhiteMedium: 'var(--ui-text-white-medium)',
  btnBg: 'var(--ui-btn-bg)',
  btnBgSoft: 'var(--ui-btn-bg-soft)',
  borderBtn: 'var(--ui-border-btn)',
  accentEmerald: 'var(--ui-accent-emerald)',
  accentEmeraldBg: 'var(--ui-accent-emerald-bg)',
  accentDarkgreen: 'var(--ui-accent-darkgreen)',
  accentAmberdark: 'var(--ui-accent-amberdark)',
  accentReddark: 'var(--ui-accent-reddark)',
  accentDarkergreen: 'var(--ui-accent-darkergreen)',
  accentDarkblue: 'var(--ui-accent-darkblue)',
  borderLight: 'var(--ui-border-light)',
  borderGray: 'var(--ui-border-gray)',
  borderGrayLight: 'var(--ui-border-gray-light)',
  borderGrayDim: 'var(--ui-border-gray-dim)',
  borderIndigo: 'var(--ui-border-indigo)',
  borderBlackLight: 'var(--ui-border-black-light)',
  borderBlackDim: 'var(--ui-border-black-dim)',
  borderAmber: 'var(--ui-border-amber)',
  textGrayLow: 'var(--ui-text-gray-low)',
  textGrayLower: 'var(--ui-text-gray-lower)',
  textGrayDark: 'var(--ui-text-gray-dark)',
  textGray4: 'var(--ui-text-gray4)',
  textGray5: 'var(--ui-text-gray5)',
  textGold: 'var(--ui-text-gold)',
  textWhiteSoft: 'var(--ui-text-white-soft)',
  textWhite: 'var(--ui-text-white)',
  textWhiteDim: 'var(--ui-text-white-dim)',
  chatPlayer: 'var(--ui-chat-player)',
  chatMonster: 'var(--ui-chat-monster)',
  chatHeal: 'var(--ui-chat-heal)',
  chatLoot: 'var(--ui-chat-loot)',
  chatMvp: 'var(--ui-chat-mvp)',
  chatDefault: 'var(--ui-chat-default)',

  /* Rarity Tokens */
  rarityCommon: 'var(--rarity-common)',
  rarityCommonBg: 'var(--rarity-common-bg)',
  rarityUncommon: 'var(--rarity-uncommon)',
  rarityUncommonBg: 'var(--rarity-uncommon-bg)',
  rarityRare: 'var(--rarity-rare)',
  rarityRareBg: 'var(--rarity-rare-bg)',
  rarityEpic: 'var(--rarity-epic)',
  rarityEpicBg: 'var(--rarity-epic-bg)',
  rarityLegendary: 'var(--rarity-legendary)',
  rarityLegendaryBg: 'var(--rarity-legendary-bg)',
} as const;

export const fontSizes = {
  title: '18px',
  name: '16px',
  normal: '14px',
  secondary: '12px',
} as const;

export const radii = {
  sm: 4,
  md: 6,
  lg: 8,
  xl: 12,
  full: 9999,
} as const;

export const shadows = {
  sm: {
    shadowColor: 'rgba(0,0,0,0.15)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  md: {
    shadowColor: 'rgba(0,0,0,0.25)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 4,
  },
  window: {
    shadowColor: 'rgba(0,0,0,0.4)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 16,
  },
} as const;

export const hudScale = {
  permanentMaxPercent: 20,
  gameplayMinPercent: 80,
} as const;

export const hudOpacity = {
  critical: 0.95,
  primary: 0.9,
  secondary: 0.85,
  tertiary: 0.7,
  dead: 0.5,
} as const;

export const slotSize = {
  sm: 36,
  md: 44,
  lg: 52,
} as const;

export type SpacingKey = keyof typeof spacing;
export type RadiiKey = keyof typeof radii;
export type FontSizeKey = keyof typeof fontSizes;
export type HudOpacityKey = keyof typeof hudOpacity;
